/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/generate-component-factory.js to modify the generation of this file.

import ExamDetails from 'feature/ExamDetails/client/components/ExamDetails';
import Address from 'feature/ExamDetails/client/components/Address';
import Name from 'feature/ExamDetails/client/components/Name';
import NameOnCertificate from 'feature/ExamDetails/client/components/NameOnCertificate';
import Email from 'feature/ExamDetails/client/components/Email';
import Phone from 'feature/ExamDetails/client/components/Phone';
import ExamLocation from 'feature/ExamDetails/client/components/ExamLocation';
import ExamAccommodation from 'feature/ExamDetails/client/components/ExamAccommodation';
import Education from 'feature/Education/client/components/Education';
import AcademicEducation from 'feature/Education/client/components/AcademicEducation';
import AcademicEducationView from 'feature/Education/client/components/AcademicEducationView';
import AcademicEducationViewHeading from 'feature/Education/client/components/AcademicEducationViewHeading';
import AcademicEducationSummary from 'feature/Education/client/components/AcademicEducationSummary';
import ProfessionalEducation from 'feature/Education/client/components/ProfessionalEducation';
import ProfessionalEducationView from 'feature/Education/client/components/ProfessionalEducationView';
import ProfessionalEducationSummary from 'feature/Education/client/components/ProfessionalEducationSummary';
import RequirementsContainer from 'feature/Education/client/components/RequirementsContainer';
import Agreements from 'feature/ExamDetails/client/components/Agreements';
import Heading from 'feature/PageComponents/client/components/Heading';
import HtmlContent from 'feature/PageComponents/client/components/HtmlContent';
import Analytics from 'feature/PageComponents/client/components/Analytics';
import ContinueButton from 'foundation/Workflow/client/components/ContinueButton';
import AdobeAnalytics from 'foundation/Analytics/client/components/AdobeAnalytics';
import ExamDetailsSubmitButton from 'feature/ExamDetails/client/components/ExamDetailsSubmitButton';
import EducationContinueButton from 'feature/Education/client/components/EducationContinueButton';
import OneColumn from './components/OneColumn';
import OneColumnCenter from './components/OneColumnCenter';
import TwoColumns_8_4 from './components/TwoColumns-8-4';
import ApplicationStart from 'feature/AppStart/client/components/ApplicationStart';
import EditSummariesStart from 'feature/AppStart/client/components/EditSummariesStart';
import AuditStart from 'feature/AppStart/client/components/AuditStart';
import EligibleToPayStart from 'feature/AppStart/client/components/EligibleToPayStart';
import LandingPageRedirect from 'feature/AppStart/client/components/LandingPageRedirect';
import Experience from 'feature/Experience/client/components/Experience';
import ExperiencePdf from 'feature/Experience/client/components/ExperiencePdf';
import ExperienceWorktypePdf from 'feature/Experience/client/components/ExperienceWorktypePdf';
import ProjectExperience from 'feature/Experience/client/components/Project';
import AgileExperience from 'feature/Experience/client/components/Agile';
import ProgramExperience from 'feature/Experience/client/components/Program';
import PortfolioExperience from 'feature/Experience/client/components/Portfolio';
import BusinessAnalysisExperience from 'feature/Experience/client/components/BusinessAnalysis';
import ExperienceSummary from 'feature/Experience/client/components/ExperienceSummary';
import FixedScrolling from 'feature/PageComponents/client/components/FixedScrolling';
import ExperienceContinueButton from 'feature/Experience/client/components/ExperienceContinueButton';
import Information from 'feature/PageComponents/client/components/Information';
import SubmitButton from 'feature/PageComponents/client/components/SubmitButton';
import RequirementsMetBadge from 'feature/PageComponents/client/components/RequirementsMetBadge';
import Breadcrumbs from 'feature/PageComponents/client/components/Breadcrumbs';
import Redirect from 'feature/PageComponents/client/components/Redirect';
import AuditInformation from 'feature/Landing/client/components/AuditInformation';
import ApplicationStartDummy from 'feature/AppStart/client/components/ApplicationStartDummy';
import ExperienceSummaries from 'feature/ExperienceSummaries/client/components/ExperienceSummaries';
import PaynowButton from 'feature/Landing/client/components/PaynowButton';
import ExperienceSummariesQA from 'feature/ExperienceSummaries/client/components/ExperienceSummariesQA';
import ExperienceSummariesSummary from 'feature/ExperienceSummaries/client/components/ExperienceSummariesSummary';
import ExperienceSummariesContinueButton from 'feature/ExperienceSummaries/client/components/ExperienceSummariesContinueButton';
import EditExperienceSummaries from 'feature/ExperienceSummaries/client/components/EditExperienceSummaries';
import EditExperienceSummariesQA from 'feature/ExperienceSummaries/client/components/EditExperienceSummariesQA';
import EditExperienceSummariesSummary from 'feature/ExperienceSummaries/client/components/EditExperienceSummariesSummary';
import EditExperienceSummariesSubmitButton from 'feature/ExperienceSummaries/client/components/EditExperienceSummariesSubmitButton';
import InformationColumnView from 'feature/PageComponents/client/components/InformationColumnView';
import ApplicationAudit from 'feature/Audit/client/components/ApplicationAudit';
import AuditBanner from 'feature/Audit/client/components/AuditBanner';
import ExperienceReference from 'feature/Audit/client/components/ExperienceAudit';
import ProfessionalEducationAuditUpload from 'feature/Audit/client/components/ProfessionalEducationAudit';
import AcademicEducationAuditUpload from 'feature/Audit/client/components/AcademicEducationAudit';
import AuditSubmitButton from 'feature/Audit/client/components/AuditSubmitButton';
import ThreeColumns from './components/ThreeColumns';
import Header from './components/Header';
import Footer from './components/Footer';
import ExamStart from 'feature/AppStart/client/components/ExamStart';

const components = new Map();

//Feature.Audit
components.set('AuditBanner', AuditBanner);
components.set('ExperienceReference', ExperienceReference);
components.set('ProfessionalEducationAuditUpload', ProfessionalEducationAuditUpload);
components.set('AcademicEducationAuditUpload', AcademicEducationAuditUpload);
components.set('AuditSubmitButton', AuditSubmitButton);

//Feature.ExamDetails
components.set('ExamDetails', ExamDetails);
components.set('ContactAddress', Address);
components.set('NameOnIdentification', Name);
components.set('NameOnCertificate', NameOnCertificate);
components.set('EmailAddress', Email);
components.set('PhoneNumber', Phone);
components.set('ExamLocation', ExamLocation);
components.set('ExamAccommodation', ExamAccommodation);
components.set('ExamDetailsSubmitButton', ExamDetailsSubmitButton);

//Feature.Education
components.set('Education', Education);
components.set('AcademicEducation', AcademicEducation);
components.set('AcademicEducationView', AcademicEducationView);
components.set('AcademicEducationViewHeading', AcademicEducationViewHeading);
components.set('AcademicEducationSummary', AcademicEducationSummary);
components.set('ProfessionalEducation', ProfessionalEducation);
components.set('ProfessionalEducationView', ProfessionalEducationView);
components.set('ProfessionalEducationSummary', ProfessionalEducationSummary);
components.set('EducationContinueButton', EducationContinueButton);
components.set('Agreements', Agreements);

//Feature.Experience
components.set('Experience', Experience);
components.set('ProjectExperience', ProjectExperience);
components.set('AgileExperience', AgileExperience);
components.set('ProgramExperience', ProgramExperience);
components.set('PortfolioExperience', PortfolioExperience);
components.set('BusinessAnalysisExperience', BusinessAnalysisExperience);
components.set('ExperienceSummary', ExperienceSummary);
components.set('ExperiencePdf', ExperiencePdf);
components.set('ExperienceWorktypePdf', ExperienceWorktypePdf);
components.set('ExperienceContinueButton', ExperienceContinueButton);

//Feature.ExperienceSummaries
components.set('ExperienceSummaries', ExperienceSummaries);
components.set('ExperienceSummariesQA', ExperienceSummariesQA);
components.set('ExperienceSummariesSummary', ExperienceSummariesSummary);
components.set('ExperienceSummariesContinueButton', ExperienceSummariesContinueButton);
components.set('EditExperienceSummaries', EditExperienceSummaries);
components.set('EditExperienceSummariesQA', EditExperienceSummariesQA);
components.set('EditExperienceSummariesSummary', EditExperienceSummariesSummary);
components.set('EditExperienceSummariesSubmitButton', EditExperienceSummariesSubmitButton);

//Feature Landing
components.set('PaynowButton', PaynowButton);
components.set('AuditInformation', AuditInformation);
components.set('ApplicationAudit', ApplicationAudit);

//Feature.PageComponents
components.set('Heading', Heading);
components.set('Analytics', Analytics);
components.set('HtmlContent', HtmlContent);
components.set('Information', Information);
components.set('InformationColumnView', InformationColumnView);
components.set('SubmitButton', SubmitButton);
components.set('FixedScrolling', FixedScrolling);
components.set('RequirementsMetBadge', RequirementsMetBadge);
components.set('RequirementsContainer', RequirementsContainer);
components.set('Breadcrumbs', Breadcrumbs);
components.set('Redirect', Redirect);

//Feature Application Start
components.set('ApplicationStart', ApplicationStart);
components.set('EditSummariesStart', EditSummariesStart);
components.set('AuditStart', AuditStart);
components.set('ApplicationStartDummy', ApplicationStartDummy);
components.set('EligibleToPayStart', EligibleToPayStart);
components.set('LandingPageRedirect', LandingPageRedirect);
components.set('ExamStart', ExamStart);

//Foundation.Workflow
components.set('ContinueButton', ContinueButton);

//Foundation.Analytics
components.set('AdobeAnalytics', AdobeAnalytics);

//Project
components.set('OneColumn', OneColumn);
components.set('OneColumnCenter', OneColumnCenter);
components.set('TwoColumns-8-4', TwoColumns_8_4);
components.set('ThreeColumns', ThreeColumns);
components.set('Header', Header);
components.set('Footer', Footer);


export default function componentFactory(componentName) {
  return components.get(componentName);
};
