const config = {
	SITECORE_JSS_APP_NAME: "#SITECORE_JSS_APP_NAME#",
	SITECORE_JSS_SERVER_BUNDLE: "#SITECORE_JSS_SERVER_BUNDLE#",
	SITECORE_API_HOST: "#SITECORE_API_HOST#",
	SITECORE_LAYOUT_SERVICE_ROUTE: "#SITECORE_LAYOUT_SERVICE_ROUTE#", 
	SITECORE_API_KEY: "#SITECORE_API_KEY#",
	SITECORE_PATH_REWRITE_EXCLUDE_ROUTES: "#SITECORE_PATH_REWRITE_EXCLUDE_ROUTES#",
	SITECORE_ENABLE_DEBUG: "#SITECORE_ENABLE_DEBUG#" == "true",
    SITECORE_NODE_SERVER_PORT: "#SITECORE_NODE_SERVER_PORT#",
    DISABLE_SSR : true
}
module.exports = config;