import { createAction } from "redux-actions";

export const FETCH_APPLICATION_REQUIREMENTS_REQUEST = "FETCH_APPLICATION_REQUIREMENTS_REQUEST";
export const FETCH_APPLICATION_REQUIREMENTS_REQUESTED = "FETCH_APPLICATION_REQUIREMENTS_REQUESTED";
export const FETCH_APPLICATION_REQUIREMENTS_SUCCESS = "FETCH_APPLICATION_REQUIREMENTS_SUCCESS";
export const FETCH_APPLICATION_REQUIREMENTS_FAILURE = "FETCH_APPLICATION_REQUIREMENTS_FAILURE";

export const fetchAppRequirements = createAction(FETCH_APPLICATION_REQUIREMENTS_REQUEST, data => data);
export const fetchAppRequirementsRequested = createAction(FETCH_APPLICATION_REQUIREMENTS_REQUESTED);
export const fetchAppRequirementsSuccess = createAction(FETCH_APPLICATION_REQUIREMENTS_SUCCESS, data => data);
export const fetchAppRequirementsFailure = createAction(FETCH_APPLICATION_REQUIREMENTS_FAILURE, data => data);
