/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.js to modify the generation of this file.
module.exports = {
  "sitecoreApiKey": "{7162987E-1BD9-4E8A-9CE4-F75101E17C99}",
  "sitecoreApiHost": "https://www.erpint.pmi.org",
  "jssAppName": "cert-app",
  "sitecoreInstanceUrl": "https://www.erpint.pmi.org",
  "authReturnRoot": "https://certification.erpint.pmi.org",
  "profileApiServiceRoot": "https://cert-prof-api.int.pmi.org/",
  "applicationApiServiceRoot": "https://cert-app-api.int.pmi.org/",
  "orchestrationApiServiceRoot": "https://cert-orchestration-api.int.pmi.org/",
  "certificationApiServiceRoot": "https://cert-cert-api.int.pmi.org/",
  "pageNotFoundPath": "/landing/sorry?errorCode=PageNotFound",
  "defaultLanguage": "en",
  "graphQLEndpointPath": "/api/cert-app",
  "graphQLEndpoint": "https://www.erpint.pmi.org/api/cert-app?sc_apikey={7162987E-1BD9-4E8A-9CE4-F75101E17C99}"
};